In [1]:
from CandleNet.DataAccess import TickerAccessor
from CandleNet import TickerContainer, IndexContainer, combine_index
import pandas as pd

In [4]:
idx = IndexContainer(
    index="GSPC",
    period="1y",
    interval="1d"
)

[*********************100%***********************]  503 of 503 completed

1 Failed download:
['AEP']: Timeout('Failed to perform, curl: (28) Connection timed out after 10014 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')

In [3]:
idx._data

Ticker,AAPL,AMGN,AMZN,AXP,BA,CAT,CRM,CSCO,CVX,DIS,...,MSFT,NKE,NVDA,PG,SHW,TRV,UNH,V,VZ,WMT
Price,Close,Close,Close,Close,Close,Close,Close,Close,Close,Close,...,Volume,Volume,Volume,Volume,Volume,Volume,Volume,Volume,Volume,Volume
Date,,,,,,,,,,,,,,,,,,,,,
2024-08-20,225.460693,320.498901,178.880005,250.362991,172.100006,337.950378,260.309174,48.899017,139.953049,88.964729,...,16387600,7863100,300087400,4513600,1739800,667200,1677500,6803600,8784000,14434000
2024-08-21,225.351212,321.084167,180.110001,243.655777,173.429993,337.625519,259.563568,49.103413,140.562424,89.936264,...,16067300,6915900,257883600,4082000,1238400,761300,2844300,6639700,13683400,14832000
2024-08-22,223.489883,316.577393,176.130005,245.100098,172.759995,337.024994,257.078186,48.879551,140.958984,89.143173,...,19361900,8485500,376189100,4097300,1077700,776500,2282000,4425200,13529600,16511100
2024-08-23,225.789169,320.742737,177.039993,248.602097,174.960007,342.980743,262.456543,49.385677,142.787109,89.777641,...,18493800,9219700,323230300,4771300,1358600,1142600,2376400,3697400,11757300,12299100
2024-08-26,226.127594,318.772278,175.500000,251.154404,173.479996,345.687897,263.729065,49.434334,143.638321,90.987099,...,13152800,7853300,331964700,6472400,1359200,697200,1800000,4612200,10309500,9508200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-08-13,233.330002,289.329987,224.559998,306.869995,233.369995,413.700012,237.029999,70.400002,155.869995,116.639999,...,19619200,13472600,179871700,5812400,2880900,1409200,19480300,5693400,14327700,19398500
2025-08-14,232.779999,290.290009,230.979996,307.730011,233.190002,417.500000,233.369995,69.300003,155.160004,116.309998,...,20269100,7990500,129554000,6343700,2615100,1506200,25011100,6224000,10582800,10858400
2025-08-15,231.589996,296.470001,231.029999,305.470001,235.259995,407.790009,242.440002,66.199997,156.550003,115.389999,...,25213300,9767700,156602200,7121700,1785100,1295700,68198500,4946600,21239200,13604900
2025-08-18,230.889999,292.619995,231.490005,307.049988,232.410004,412.640015,243.970001,66.949997,155.320007,116.550003,...,23760600,9069100,132008000,8274500,2097300,968400,39600500,3999600,12692100,11656100
2025-08-19,230.559998,295.549988,228.009995,306.100006,225.000000,416.089996,246.000000,66.760002,152.000000,116.269997,...,20802663,6870318,183191247,7439296,2087344,1354127,21822211,3144047,13298961,12999374

In [4]:
idx.nameless_data

Price            Close        High         Low        Open    Volume
Date
2024-08-20  225.460693  226.117640  224.405606  224.724131  30299000
2024-08-21  225.351212  226.923894  224.007474  225.470666  34765500
2024-08-22  223.489883  227.282232  222.862797  226.734776  43695300
2024-08-23  225.789169  227.162781  223.290802  224.614643  38677300
2024-08-26  226.127594  226.227137  222.852841  225.709541  30602200
...                ...         ...         ...         ...       ...
2025-08-13  100.754669  102.570428  100.614996  101.911970  19398500
2025-08-14  100.614998  101.203627  100.485304  100.984138  10858400
2025-08-15  100.000000  100.769997   99.540001  100.629997  13604900
2025-08-18  100.699997  100.879997   99.919998  100.000000  11656100
2025-08-19  101.290001  102.425003  100.809998  100.959999  12999374

[7500 rows x 5 columns]

In [6]:
import datetime as dt

dt.datetime.now().isoformat()

'2025-08-21T13:58:06.821080'